<?php
declare(strict_types=1);

define('_CALIBRE_OPDS', true);
session_start();
require_once __DIR__ . '/bootstrap.php';

use CalibreOpds\Config;
use CalibreOpds\Auth;

$configured = Config::load();

// ── Auth gate ─────────────────────────────────────────────────────────────────
if ($configured && !Auth::check()) {
    $loginError = '';
    if ($_SERVER['REQUEST_METHOD'] === 'POST' && isset($_POST['api_key'])) {
        if (Auth::attempt($_POST['api_key'])) {
            header('Location: about.php');
            exit;
        }
        $loginError = 'Invalid key.';
    }
    $siteTitle = Config::get('READER_TITLE', 'Calibre Bookshelf');
    $return    = 'about.php';
    include __DIR__ . '/views/login.php';
    exit;
}

// ── Download generated script as ZIP ─────────────────────────────────────────
if (isset($_GET['download']) && $_GET['download'] === 'script' && Auth::check() && $configured) {
    $serverUrl = rtrim(Config::get('BOOKS_API_URL'), '/') . '/api.php';
    $apiKey    = Config::get('API_KEY');
    $ncUser    = Config::get('NC_USER');
    $ncPass    = Config::get('NC_PASS');

    $scriptContent = generateScript($serverUrl, $apiKey, $ncUser, $ncPass);
    
    // Create ZIP file in memory
    $zip = new ZipArchive();
    $zipName = 'kobo_calibre.zip';
    $tempFile = tempnam(sys_get_temp_dir(), 'kobo_');
    
    if ($zip->open($tempFile, ZipArchive::CREATE | ZipArchive::OVERWRITE) === true) {
        $zip->addFromString('kobo_calibre.sh', $scriptContent);
        $zip->close();
        
        // Serve the ZIP file
        header('Content-Type: application/zip');
        header('Content-Disposition: attachment; filename="' . $zipName . '"');
        header('Content-Length: ' . filesize($tempFile));
        header('Cache-Control: no-store');
        
        readfile($tempFile);
        unlink($tempFile);
        exit;
    } else {
        // Fallback to direct .sh download if ZIP creation fails
        header('Content-Type: application/octet-stream');
        header('Content-Disposition: attachment; filename="kobo_calibre.sh"');
        header('Cache-Control: no-store');
        echo $scriptContent;
        exit;
    }
}


function generateScript(string $serverUrl, string $apiKey, string $ncUser, string $ncPass): string
{
    // Using a Nowdoc (<<<'SHELL') to ensure PHP doesn't try to parse shell variables like $1 or $$.
    // We use %% for percent signs to escape them for the sprintf function.
    $template = <<<'SHELL'
#!/bin/sh
# kobo_calibre.sh — Calibre OPDS sync for Kobo
# Generated by Calibre OPDS Reader

SERVER_URL="%s"
API_KEY="%s"
NC_USER="%s"
NC_APP_PASSWORD="%s"
BOOKS_DIR="/mnt/onboard/Books"
LOG_FILE="/mnt/onboard/kobo_sync.log"
USER_AGENT="KoboReader"

mkdir -p "${BOOKS_DIR}"

log() {
    echo "$(date '+%%Y-%%m-%%d %%H:%%M:%%S') - $1" >> "${LOG_FILE}"
    if command -v nickel_message >/dev/null 2>&1; then
        nickel_message "$1" 2>/dev/null
    fi
}

log "=== Sync Started ==="

# Remount as writable [cite: 6, 16]
mount -o remount,rw /mnt/onboard 2>/dev/null

# Generate Base64 auth [cite: 2, 12, 22]
B64_AUTH=$(echo -n "${NC_USER}:${NC_APP_PASSWORD}" | base64 | tr -d '\n\r')

log "Fetching book list from server..."
RAW_RESPONSE="/tmp/books_raw_$$.json"

# Fetch the queue [cite: 2, 12, 22]
wget --timeout=30 --tries=2 --user-agent "$USER_AGENT" \
    -q -O "${RAW_RESPONSE}" "${SERVER_URL}?key=${API_KEY}&action=list" 2>> "${LOG_FILE}"

if [ ! -s "${RAW_RESPONSE}" ]; then
    log "ERROR: Failed to fetch queue"
    rm -f "${RAW_RESPONSE}"
    exit 1
fi

# Process books [cite: 4, 14, 24]
tr '}' '\n' < "${RAW_RESPONSE}" | grep '"synced_status":"pending"' > "/tmp/pending_books_$$.txt"

INDEX=0
while IFS= read -r book_line; do
    [ -z "$book_line" ] && continue

    # Extract info [cite: 5, 15, 25]
    CURRENT_FILE=$(echo "$book_line" | sed 's/.*"file":"\([^"]*\)".*/\1/')
    CURRENT_URL=$(echo "$book_line" | sed 's/.*"url":"\([^"]*\)".*/\1/' | sed 's/\\//g')

    if [ -n "$CURRENT_FILE" ] && [ -n "$CURRENT_URL" ]; then
        dest="${BOOKS_DIR}/${CURRENT_FILE}"
        
        # Decide if we need ? or & [cite: 6, 16, 26]
        if echo "$CURRENT_URL" | grep -q "?"; then 
            DOWNLOAD_URL="${CURRENT_URL}&key=${API_KEY}"
        else 
            DOWNLOAD_URL="${CURRENT_URL}?key=${API_KEY}"
        fi

        log "Downloading: $CURRENT_FILE"
        if wget -T 60 --user-agent "$USER_AGENT" --header "Authorization: Basic ${B64_AUTH}" -O "$dest" "$DOWNLOAD_URL" 2>> "${LOG_FILE}"; then
            if [ -s "$dest" ]; then
                log "  -> SUCCESS"
                # Mark as synced [cite: 9, 19, 30]
                wget -q -T 10 --user-agent "$USER_AGENT" -O /dev/null "${SERVER_URL}?key=${API_KEY}&action=mark_synced&index=${INDEX}"
            fi
        fi
    fi
    INDEX=$((INDEX + 1))
done < "/tmp/pending_books_$$.txt"

rm -f "${RAW_RESPONSE}" "/tmp/pending_books_$$.txt"
log "=== Sync Finished ==="
SHELL;

    // Apply configuration [cite: 21]
    $output = sprintf($template, $serverUrl, $apiKey, $ncUser, $ncPass);

    // CRITICAL: Remove all \r (Carriage Returns) to ensure Unix format (LF)
    // This stops the "unexpected word (expecting ")")" error.
    return str_replace("\r", "", $output);
}

$siteTitle  = Config::get('READER_TITLE', 'Calibre Bookshelf');
$booksApiUrl = rtrim(Config::get('BOOKS_API_URL'), '/');
$canDownload = Auth::check() && $configured && $booksApiUrl !== '' && Config::get('API_KEY') !== '';
$queueCount = \CalibreOpds\Queue::count();
?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>About — <?= htmlspecialchars($siteTitle) ?></title>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Noto+Sans+JP:wght@300;400;500&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="style.css">
</head>
<body>

<header>
    <div class="wrap header-inner">
        <a class="site-title" href="index.php"><?= htmlspecialchars($siteTitle) ?></a>
        <nav class="site-nav">
            <a class="nav-link" href="index.php">📚 Reader</a>
            <a class="nav-link" href="config.php?tab=queue">
                ☰ Queue<?php if ($queueCount > 0): ?> <span class="badge"><?= $queueCount ?></span><?php endif; ?>
            </a>
            <a class="nav-link active" href="about.php">ℹ About</a>
            <a class="nav-link" href="config.php">⚙ Config</a>
            <?php if (Auth::check()): ?>
                <a class="nav-link logout" href="index.php?logout=1">⏻</a>
            <?php endif; ?>
        </nav>
    </div>
</header>

<div class="wrap about-wrap">

    <div class="about-section">
        <h2>Calibre OPDS Reader</h2>
        <p>
            A self-hosted web reader that browses your Calibre library via OPDS, served by the
            <a href="https://github.com/oldnomad/calibre_opds" target="_blank" rel="noopener">Calibre2OPDS</a>
            app for Nextcloud. Books can be downloaded directly to your browser or queued for your Kobo e-reader.
        </p>
    </div>

    <div class="about-section">
        <h2>Requirements</h2>
        <ul class="about-list">
            <li>A running <strong>Nextcloud</strong> instance</li>
            <li>The <strong>Calibre2OPDS</strong> Nextcloud app (<a href="https://github.com/oldnomad/calibre_opds" target="_blank" rel="noopener">github.com/oldnomad/calibre_opds ↗</a>)</li>
            <li>A Nextcloud <strong>app password</strong> (not your account password)</li>
            <li>PHP 8.0+ with <code>curl</code>, <code>simplexml</code>, and <code>zip</code> extensions</li>
        </ul>
    </div>

    <div class="about-section">
        <h2>Kobo Integration</h2>
        <p>
            When you click <strong>⇢ Kobo</strong> on any book in the reader, it is added to your Kobo queue.
            A shell script running on your Kobo polls the queue via the built-in API and downloads new books automatically.
        </p>
        <p>
            The Kobo script uses your Nextcloud credentials to download files directly from your Nextcloud instance —
            your books never pass through any third-party service.
        </p>
    </div>

    <div class="about-section">
        <h2>Kobo Setup — Step by Step</h2>

        <div class="step-list">
            <div class="step">
                <div class="step-num">1</div>
                <div class="step-body">
                    <strong>Install NickelMenu on your Kobo</strong><br>
                    Download NickelMenu from
                    <a href="https://pgaskin.net/NickelMenu/" target="_blank" rel="noopener">pgaskin.net/NickelMenu ↗</a>
                    and copy the <code>.kobo</code> folder to your Kobo's storage root.
                    Safely eject and reboot the device.
                </div>
            </div>

            <div class="step">
                <div class="step-num">2</div>
                <div class="step-body">
                    <strong>Download the sync script</strong><br>
                    <?php if ($canDownload): ?>
                        <a class="btn btn-primary" href="about.php?download=script">
                            ↓ Download kobo_calibre.zip
                        </a>
                        <span class="field-hint" style="display:block;margin-top:0.4rem">
                            Contains <code>kobo_calibre.sh</code> pre-filled with your configuration. Extract the ZIP on your computer, then copy the script to your Kobo. 
							<p>
								Set permission before adding to Kobo: <br>
							LINUX/MAC <code>chmod +x kobo_calibre.sh</code> 
								<br>WINDOWS 
								<code>icacls X:\kobo_calibre.sh /grant "Everyone:RX"</code></p>
                        </span>
                    <?php else: ?>
                        <span class="field-hint">
                            Configure <strong>This app's URL</strong> and <strong>Access key</strong> in
                            <a href="config.php">Settings</a> first — then return here to download a pre-filled script.
                        </span>
                    <?php endif; ?>
                </div>
            </div>

            <div class="step">
                <div class="step-num">3</div>
                <div class="step-body">
                    <strong>Extract and copy the script to your Kobo</strong><br>
                    Extract the ZIP file to get <code>kobo_calibre.sh</code>, then place it at:
                    <div class="code-block">/mnt/onboard/.adds/kobo_calibre.sh</div>
                    <span class="field-hint">
                        The <code>.adds</code> folder is hidden. On Linux/Mac use a file manager that shows hidden files,
                        or connect via SSH/MTP.
                    </span>
                </div>
            </div>

            <div class="step">
                <div class="step-num">4</div>
                <div class="step-body">
                    <strong>Configure NickelMenu</strong><br>
                    Create or edit the file at:
                    <div class="code-block">/mnt/onboard/.adds/nm/config</div>
                    Add these two lines:
                    <div class="code-block" id="nmConfig">menu_item :main :Sync Books   :cmd_spawn   :bin/sh /mnt/onboard/.adds/kobo_calibre.sh
menu_item :main :Rescan Books :nickel_misc :rescan_books_full</div>
                    <button class="btn btn-secondary" onclick="copyNm()">Copy lines</button>
                </div>
            </div>

            <div class="step">
                <div class="step-num">5</div>
                <div class="step-body">
                    <strong>Sync books</strong><br>
                    Safely eject your Kobo and reboot it. You should now see
                    <strong>Sync Books</strong> and <strong>Rescan Books</strong> in the main menu.
                    Tap <strong>Sync Books</strong> to download queued books to <code>/mnt/onboard/Books</code>.
                    Tap <strong>Rescan Books</strong> afterwards to add them to your library.
                </div>
            </div>
        </div>
    </div>

    <div class="about-section">
        <h2>Workflow</h2>
        <ol class="about-list">
            <li>Browse your Calibre library in the Reader</li>
            <li>Click <strong>⇢ Kobo</strong> on any book to queue it</li>
            <li>On your Kobo, tap <strong>Sync Books</strong> from the NickelMenu</li>
            <li>Tap <strong>Rescan Books</strong> to add downloaded books to your library</li>
            <li>Manage the queue from the <a href="config.php?tab=queue">Queue</a> page</li>
        </ol>
    </div>

    <div class="about-section">
        <h2>API Endpoints</h2>
        <p class="field-hint" style="margin-bottom:0.75rem">
            All API calls require <code>?key=YOUR_ACCESS_KEY</code>.
        </p>
        <table class="api-table">
            <tr><td><code>api.php?action=list</code></td><td>JSON array of queued books</td></tr>
            <tr><td><code>api.php?action=add_link&amp;url=…&amp;name=…</code></td><td>Add a book to the queue</td></tr>
            <tr><td><code>api.php?action=remove&amp;index=N</code></td><td>Remove item by index</td></tr>
            <tr><td><code>api.php?action=clear</code></td><td>Clear the entire queue</td></tr>
        </table>
    </div>


    <div class="about-section">
        <h2>Support & Contact</h2>
        <p>
            For questions, bug reports, or feature requests, please open an issue on 
            <a href="https://github.com/marisabelmunoz/calibre-kobo-bridge" target="_blank" rel="noopener">GitHub Issues</a>.
        </p>
        <p>
            📧 Email: <b>web [AT] marisabel DOT [nl]</b>
        </p>
        <p class="field-hint">
            When reporting issues, please include:<br>
            - Your PHP version<br>
            - Nextcloud version and Calibre2OPDS app version<br>
            - Any relevant error messages from logs
        </p>
        <p>This is a hobby persoanl project. I might not know the answers to all the questions, but I might be able to still help. 
        I only own <b>Kobo Clara Colour</b>. So I have not tested this with other Kobo's.</p>
    </div>
</div>

<footer>
    <div class="wrap footer-inner">
        <span><a href="https://github.com/marisabelmunoz/calibre-kobo-bridge" target="_blank" rel="noopener">Calibre OPDS Reader ↗</a></span>
        <a href="https://github.com/oldnomad/calibre_opds" target="_blank" rel="noopener">Calibre2OPDS ↗</a>
        <a href="https://pgaskin.net/NickelMenu/" target="_blank" rel="noopener">NickelMenu ↗</a>
    </div>
</footer>

<div id="toast"></div>

<script>
function toast(msg, isErr = false) {
    const t = document.getElementById('toast');
    t.textContent = msg;
    t.className = 'show' + (isErr ? ' err' : '');
    clearTimeout(t._tid);
    t._tid = setTimeout(() => t.className = '', 3000);
}
function copyNm() {
    const text = document.getElementById('nmConfig').textContent;
    navigator.clipboard.writeText(text).then(
        () => toast('✓ Copied to clipboard'),
        () => toast('✗ Could not copy', true)
    );
}
</script>
</body>
</html>